### ISSUE TITLE
capistranoでamazon linuxにデプロイする際にGem Load Error is: can't create Java VMが発生する

### ISSUE THREAD

**Issue by tomohiroo** [yalab/kuromoji-ruby#2]
railsプロジェクトでkuromoji-rubyをインストールし、capistranoでamazon linuxにデプロイする時に以下のエラーが発生しました。

```
00:08 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:08 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 Bundler::GemRequireError: There was an error while trying to load the gem 'zipang'.
      01 Gem Load Error is: can't create Java VM
      01 Backtrace for gem load error is:
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `load'
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `<mod…00:08 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:08 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 Bundler::GemRequireError: There was an error while trying to load the gem 'zipang'.
      01 Gem Load Error is: can't create Java VM
      01 Backtrace for gem load error is:
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `load'
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `<mod…00:08 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:08 deploy:migrating
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake db:migrate
      01 rake aborted!
      01 Bundler::GemRequireError: There was an error while trying to load the gem 'zipang'.
      01 Gem Load Error is: can't create Java VM
      01 Backtrace for gem load error is:
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `load'
      01 /home/tomohiroo/pecopeco/shared/bundle/ruby/2.5.0/gems/kuromoji-0.0.1/lib/kuromoji.rb:6:in `<mod…
```

irb上でkuromoji-ruby(やzipang)をrequireすることができ、rubyのコードを動かすことはできます。
また、amazon linux上で$JAVA_HOMEは設定してあります。
ローカル環境(Mac)では正常に動作します。

環境 (リモートとローカルで一致)
ruby 2.5.1
rails 5.2.1

ローカル環境
java  -version
```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

リモート環境
java -version
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Comment by tomohiroo** [comment]
もうしわけありません。
java_homeが通っていないようでした。
